USE INTERN;
-- 5question  SQL Basics: DDL & DML


CREATE TABLE DEPARTMENTS_BHARGAV(
DEPT_ID VARCHAR(10),
DEPT_NAME VARCHAR(50)
);
ALTER TABLE DEPARTMENTS_BHARGAV
MODIFY DEPT_ID VARCHAR(50) unique;
CREATE TABLE COURSES_BHARGAV (
COURSE_ID VARCHAR(10),
COURSE_NAME VARCHAR(50),
DEPT_ID VARCHAR(50));
CREATE TABLE STUDENTS_BHARGAV (
STUDENT_ID VARCHAR(10),
STUDENT_NAME VARCHAR(50),
DOB DATE,
AGE INT,
DEPT_ID VARCHAR(10));
INSERT INTO DEPARTMENTS_BHARGAV (DEPT_ID,DEPT_NAME) VALUES
("D1","COMPUTER SCIENCE"),
("D2","MATHEMATICS"),
("D3","PHYSICS");
INSERT INTO COURSES_BHARGAV (COURSE_ID,COURSE_NAME,DEPT_ID) VALUES
("C1","DBMS","D1"),
("C2","LINEAR ALGEBRA","D2"),
("C3","QUANTUM MECHANICS","D3");
INSERT INTO STUDENTS_BHARGAV VALUES
("S1","RAVI","2002-06-10",22,"D1"),
("S2","SNEHA","2001-03-15",23,"D2"),
("S3","ARJUN","2003-03-15",21,"D1");
SELECT * FROM STUDENTS_BHARGAV;
ALTER TABLE COURSES_BHARGAV  ADD COLUMN DURATION VARCHAR(50);
UPDATE COURSES_BHARGAV SET DURATION="2WEEKS" WHERE COURSE_NAME="DBMS";
UPDATE COURSES_BHARGAV SET DURATION="4WEEKS" WHERE COURSE_NAME="LINEAR ALGEBRA";
UPDATE COURSES_BHARGAV SET DURATION="6WEEKS" WHERE COURSE_NAME="QUANTUM MECHANCIS";
SELECT * FROM COURSES_BHARGAV;
SELECT * FROM STUDENTS_BHARGAV;
UPDATE  STUDENTS_BHARGAV SET STUDENT_NAME ="SNEHA REDDY" WHERE STUDENT_NAME="SNEHA";
DELETE FROM COURSES_BHARGAV WHERE COURSE_ID = "C3";

-- 6question  SELECT Queries & Filtering



SELECT * FROM STUDENTS_BHARGAV
WHERE AGE>21;
SELECT STUDENT_NAME,DOB FROM STUDENTS_BHARGAV
ORDER BY AGE ASC;
SELECT * FROM STUDENTS_BHARGAV
ORDER BY AGE ASC
LIMIT 2;

-- 7 question Aggregates & GROUP BY


SELECT DEPT_ID,COUNT(*) FROM STUDENTS_BHARGAV
group by DEPT_ID;
SELECT avg(AGE),DEPT_ID FROM STUDENTS_BHARGAV
group by DEPT_ID;
SELECT MAX(AGE) AS maximum , MIN(AGE) AS minimum from STUDENTS_BHARGAV;




DROP TABLE ACCOUNTS_BHARGAV;

-- 8th question Transaction Control Language


USE INTERN;
CREATE TABLE ACCOUNTS_BHARGAV(
ACCOUNT_ID VARCHAR(10),
HOLDER_NAME VARCHAR(50),
BALANCE decimal(10));
INSERT INTO ACCOUNTS_BHARGAV (account_id, holder_name, balance)
VALUES("Account 1"," Alice", 5000),
("Account 2","Bob",3000),
("Account 3"," Charlie",4000);
BEGIN;
UPDATE ACCOUNTS_BHARGAV SET BALANCE=(BALANCE-1000) WHERE ACCOUNT_ID="ACCOUNT 1";
SELECT * FROM ACCOUNTS_BHARGAV;
UPDATE ACCOUNTS_BHARGAV SET BALANCE =(BALANCE+1000) WHERE ACCOUNT_ID="ACCOUNT 2";
ROLLBACK;
SELECT *FROM ACCOUNTS_BHARGAV;
BEGIN;
UPDATE ACCOUNTS_BHARGAV SET BALANCE =(BALANCE-1000) WHERE ACCOUNT_ID="ACCOUNT 1";
SAVEPOINT AFTER_DEBIT;
UPDATE ACCOUNTS_BHARGAV SET BALANCE=(BALANCE+1000) WHERE ACCOUNT_ID ="ACCOUNT 2";
UPDATE ACCOUNTS_BHARGAV SET BALANCE=(BALANCE+500) WHERE ACCOUNT_ID="ACCOUNT 3";
ROLLBACK TO AFTER_DEBIT;
COMMIT;

-- 10th question Data Integrity & Constraints



ALTER TABLE COURSES_BHARGAV ADD COLUMN COURSE_CODE VARCHAR(50);
UPDATE COURSES_BHARGAV SET COURSE_CODE="CS101" WHERE COURSE_NAME ="DBMS";
UPDATE COURSES_BHARGAV SET COURSE_CODE="MATH205" WHERE COURSE_NAME ="LINEAR ALGEBRA";
UPDATE COURSES_BHARGAV SET COURSE_CODE="PHY303" WHERE COURSE_NAME ="QUANTUM MECHANICS";
ALTER TABLE COURSES_BHARGAV modify COLUMN COURSE_CODE VARCHAR(50) unique;
ALTER TABLE COURSES_BHARGAV ADD COLUMN CREDITS INT CHECK (CREDITS>=1 AND CREDITS<=5);
UPDATE COURSES_BHARGAV SET CREDITS=4 WHERE COURSE_NAME="DBMS";
UPDATE COURSES_BHARGAV SET CREDITS=3 WHERE COURSE_NAME="LINEAR ALGEBRA";
UPDATE COURSES_BHARGAV SET CREDITS=5 WHERE COURSE_NAME="QUANTUM MECHANICS";
SELECT * FROM COURSES_BHARGAV;
ALTER TABLE COURSES_BHARGAV
ADD foreign key (DEPT_ID)
REFERENCES DEPARTMENTS_BHARGAV(DEPT_ID);

-- 9th question Joins, Set Operations & Advanced Querying


SELECT STUDENT_NAME,DEPT_NAME FROM STUDENTS_BHARGAV 
INNER JOIN DEPARTMENTS_BHARGAV ON
STUDENTS_BHARGAV.DEPT_ID = DEPARTMENTS_BHARGAV.DEPT_ID;
SELECT COUNT(S.STUDENT_ID),D.DEPT_ID,D.DEPT_NAME FROM STUDENTS_BHARGAV S
LEFT JOIN DEPARTMENTS_BHARGAV  D ON
S.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_ID;

SELECT * FROM STUDENTS_BHARGAV S WHERE AGE >(
SELECT AVG(AGE) FROM STUDENTS_BHARGAV WHERE DEPT_ID=S.DEPT_ID
GROUP BY DEPT_ID);

WITH STUDENTS_COUNT AS(
SELECT COUNT(STUDENT_ID),D.DEPT_ID FROM 
STUDENTS_BHARGAV S LEFT JOIN DEPARTMENTS_BHARGAV D ON
S.DEPT_ID=D.DEPT_ID
group by D.DEPT_ID)
SELECT * FROM STUDENTS_COUNT;

-- 11th question . Views



CREATE VIEW STUDENT_DATA AS(
SELECT S.STUDENT_NAME,D.DEPT_NAME FROM STUDENTS_BHARGAV S LEFT JOIN 
DEPARTMENTS_BHARGAV D ON S.DEPT_ID=D.DEPT_ID);

SELECT * FROM STUDENT_DATA;

UPDATE STUDENT_DATA SET STUDENT_NAME ="BHARGAV" 
WHERE STUDENT_ID = "S1";

SELECT * FROM STUDENTS_BHARGAV;

DROP VIEW STUDENT_DATA;








SELECT * FROM STUDENTS_BHARGAV S LEFT JOIN 
COURSES_BHARGAV C ON 
S.DEPT_ID=C.DEPT_ID
WHERE COURSE_ID IS NULL;


